#cloud-config
users:
  - name: zhizuko
    gecos: Zhizuko Dot Net User
    groups: users, admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    passwd: ${zhizuko_linux_password}
package_update: true
package_upgrade: true
package_reboot_if_required: false

# disable password authentication for root user
ssh_pwauth: false

# install required packages
packages:
  - apt-transport-https
  - ca-certificates
  - certbot
  - curl
  - dos2unix
  - git
  - gnupg-agent
  - jq
  - net-tools
  - python3-certbot-nginx
  - software-properties-common
  - tree
  - zip

# render files
write_files:
- encoding: b64
  path: /tmp/mssql-install.sh
  content: ${mssql_install_script}
  permissions: "0755"
- encoding: b64
  path: /tmp/db-setup.sql
  content: ${sql_sequence}
- encoding: b64
  path: /tmp/appsettings.json
  content: ${appsettings}
- encoding: b64
  path: /etc/nginx/sites-available/${domain}.conf
  content: ${nginx_config}
- encoding: b64
  path: /etc/systemd/system/${server_name}.service
  content: ${zhizuko_unitfile}
- path: /tmp/build-project.sh
  owner: zhizuko:zhizuko
  permissions: "0755"
  defer: true
  content: |
    /usr/bin/git clone https://github.com/vegaitsourcing/website-gradimo-zajedno.git /code
    cp /tmp/appsettings.json /code/GradimoZajedno.Web/appsettings.json
    DOTNET_CLI_HOME=/dotnet dotnet build /code/GradimoZajedno.Web/GradimoZajedno.Web.csproj --configuration Prod /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
    DOTNET_CLI_HOME=/dotnet dotnet publish /code/GradimoZajedno.Web/GradimoZajedno.Web.csproj --configuration Prod /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary

# execute commands on the first boot
runcmd:
  - hostnamectl set-hostname ${server_name}
  # set bash profile for root user
  - echo "source /root/.profile" >> /root/.bash_profile
  # setup directories
  - mkdir /code /dotnet
  - chown zhizuko:zhizuko /code /dotnet
  # ufw
  - ufw allow OpenSSH
  - ufw allow "Nginx Full"
  - ufw --force enable
  # sshd
  - sed 's/#ClientAliveInterval 0/ClientAliveInterval 60/' -i /etc/ssh/sshd_config
  - sed 's/#ClientAliveCountMax 3/ClientAliveCountMax 3/' -i /etc/ssh/sshd_config
  - systemctl restart sshd.service
  # dotnet 6
  - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - dpkg -i packages-microsoft-prod.deb
  - rm packages-microsoft-prod.deb
  - apt update -y
  - apt install -y dotnet-sdk-6.0
  - echo 'export DOTNET_CLI_HOME=/dotnet' >> /root/.bashrc
  - echo 'export DOTNET_CLI_HOME=/dotnet' >> /home/zhizuko/.bashrc
  # mssql 2022
  - dos2unix /tmp/mssql-install.sh # make sure we are not using CR LF (Windows) control characters
  - /tmp/mssql-install.sh
  - chmod 644 /lib/systemd/system/mssql-server.service
  - wget -O /tmp/db.zip https://zhizuko-artifacts.s3.eu-central-1.amazonaws.com/GradimoZajedno-20230202T100418Z-001.zip
  - unzip /tmp/db.zip -d /tmp
  - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P '${mssql_sa_password}' -i /tmp/db-setup.sql -o /var/log/db-setup.log -e
  # build project
  - sudo -u zhizuko /tmp/build-project.sh
  - chown -R zhizuko:zhizuko /code
  # nginx
  - rm -rf /etc/nginx/sites-{available,enabled}/default
  - ln -s /etc/nginx/sites-available/${domain}.conf /etc/nginx/sites-enabled/
  - systemctl restart nginx
  # generate website certificate and update nginx configuration automatically
  - certbot --nginx -d ${domain} --non-interactive --agree-tos -m ${cert_contact_email} --redirect
  # zhizuko systemd unit
  - systemctl start ${project_name}.service
  - systemctl enable ${project_name}.service

# reboot
power_state:
 delay: 2
 mode: reboot
 message: Rebooting the system to finalize software installation
 timeout: 30
 condition: True

final_message: "*** System setup is complete, after $UPTIME seconds ***"